### ISSUE TITLE
Testing Updates Meta-Issue

### ISSUE THREAD

**Issue by rcabell** [NCAR/wrf_hydro_nwm_public#424]
This is a meta-issue to track all the needed updates to testing, both in configuration permutations and the testing of new capabilities. Specific issues relating a particular entry should be noted.

**Testing should include:**

- [ ] Reservoir persistence - USGS
- [ ] Reservoir persistence - Corps
- [ ] Noah (legacy LSM) build 
- [ ] NWM metadata output (Issue #423)
- [ ] CMake build

**Comment by kafitzgerald** [comment]
WRF and WRF-Hydro coupled would also be good as well as either a Hawaii and/or Puerto Rico config.

I also have some comments over in issue #345.
